"""pexpect driver for the interactive CHAPERONg umbrella-sampling pipeline.

CHAPERONg drives the whole protein-protein US workflow (stages 0-18) through
`read -p` prompts. Rather than blind-piping answers, each prompt is matched by
pattern so that skipped or re-asked questions do not desynchronise the script.

Two hooks do work that CHAPERONg leaves to the user: wiring the immobile
reference restraints into topol.top, and writing index.ndx with the pull groups.

Stage 13 renders a PyMOL movie of the steered-MD trajectory, which costs hours
of ray tracing and contributes nothing to the PMF. Every CHAPERONg entry stage
up to 13 runs it unconditionally, so the movie is skipped by splitting the work
into two sessions: the first is stopped at the movie prompt (steered MD is
complete on disk by then), the second re-enters at stage 14, which starts with
frame extraction.
"""

from __future__ import annotations

import json
import os
import re
import shutil
from dataclasses import dataclass
from pathlib import Path
from typing import Callable

from .base import RunContext, build_index, setup_restraints, verify_pull_range

try:
    import pexpect
except ImportError:  # pragma: no cover
    pexpect = None

STOP = object()

MOVIE_PROMPT = r"Enter 1 or 2 here:"
SMD_DONE = "pull.gro"


@dataclass
class Step:
    pattern: str
    response: str | Callable[[RunContext], str] | object
    before: Callable[[RunContext], None] | None = None
    label: str = ""

    def answer(self, ctx: RunContext) -> str:
        return self.response(ctx) if callable(self.response) else str(self.response)


def locate(spec: str = "run_CHAPERONg.sh") -> tuple[Path, Path]:
    """Resolve the launcher to an absolute path and the CHAPERONg root.

    pexpect looks a bare command up in the PATH of the *current* process, which
    does not necessarily contain CHAP_modules even when CHAPERONg_PATH is
    exported, so the path is resolved here instead of being handed over as a
    bare name.
    """
    candidates: list[Path] = []
    p = Path(spec).expanduser()
    if p.is_absolute() or spec.startswith((".", "/", "~")):
        candidates.append(p)
    else:
        found = shutil.which(spec)
        if found:
            candidates.append(Path(found))
        root = os.environ.get("CHAPERONg_PATH", "")
        if root:
            candidates += [Path(root) / "CHAP_modules" / spec, Path(root) / spec]

    for c in candidates:
        if c.is_file():
            script_path = c.resolve()
            parent = script_path.parent
            root = parent.parent if parent.name == "CHAP_modules" else parent
            return script_path, root

    raise RuntimeError(
        f"cannot find the CHAPERONg launcher '{spec}'. Looked in PATH and under "
        f"CHAPERONg_PATH={os.environ.get('CHAPERONg_PATH') or '<unset>'}. Either export\n"
        "  export CHAPERONg_PATH=$HOME/soft/CHAPERONg\n"
        "  export PATH=\"$PATH:$CHAPERONg_PATH/CHAP_modules\"\n"
        "or set an absolute path in protocol.yaml:\n"
        "  run:\n    chaperong: /home/you/soft/CHAPERONg/CHAP_modules/run_CHAPERONg.sh"
    )


def preflight(proto) -> tuple[Path, Path]:
    """Fail before any simulation starts if CHAPERONg is not usable."""
    script_path, root = locate(proto.run.chaperong)
    missing = [m for m in ("CHAP_deffxn.sh", "CHAP_ana.sh", "CHAP_sim.sh", "CHAP_colPar.sh")
               if not (root / "CHAP_modules" / m).is_file()]
    if missing:
        raise RuntimeError(
            f"CHAPERONg root {root} is incomplete, missing: {', '.join(missing)}. "
            "The launcher sources these modules through $CHAPERONg_PATH."
        )
    return script_path, root


def _center(ctx: RunContext) -> str:
    info = json.loads((ctx.workdir.parent / "prep.json").read_text())
    return " ".join(f"{v}" for v in info["center_nm"])


def _box(ctx: RunContext) -> str:
    info = json.loads((ctx.workdir.parent / "prep.json").read_text())
    return " ".join(f"{v}" for v in info["box_nm"])


def _wire_restraints(ctx: RunContext) -> None:
    if (ctx.workdir / "topol.top").exists():
        setup_restraints(ctx)


def _make_index(ctx: RunContext) -> None:
    """Index groups, then the last chance to sanity-check the pull budget.

    CHAPERONg asks this question at the end of stage 10, i.e. after NPT and
    before the steered MD is grompp'ed - the only point where the equilibrated
    geometry is known and md_pull.mdp can still be adjusted.
    """
    gro = "npt.gro" if (ctx.workdir / "npt.gro").exists() else "solv_ions.gro"
    build_index(ctx, gro)
    if gro == "npt.gro":
        verify_pull_range(ctx)


PYMOL_SHIM = """#!/bin/bash
# Generated by cg-us. CHAPERONg calls `pymol script.pml`, which starts the GUI
# and dies on a headless node; -c renders the same frames offscreen.
exec {prefix}{pymol} -cq "$@"
"""


def write_pymol_shim(ctx: RunContext) -> Path | None:
    """A PATH-shadowing `pymol` that runs headless, for the stage-13 movie."""
    if ctx.proto.run.skip_movie or not ctx.proto.run.pymol_headless:
        return None
    real = shutil.which("pymol")
    if not real:
        print("      [warn] pymol not found: the movie stage will fail (harmlessly) "
              "and the pipeline will carry on")
        return None
    bindir = ctx.workdir / "bin"
    bindir.mkdir(exist_ok=True)
    xvfb = shutil.which("xvfb-run")
    shim = bindir / "pymol"
    shim.write_text(PYMOL_SHIM.format(
        prefix=f'"{xvfb}" -a ' if xvfb else "",
        pymol=f'"{real}"',
    ))
    shim.chmod(0o755)
    return bindir


def _assert_smd_finished(ctx: RunContext) -> None:
    if not (ctx.workdir / SMD_DONE).exists():
        raise RuntimeError(
            f"reached the movie prompt but {SMD_DONE} is missing - steered MD did not "
            f"finish cleanly. Inspect {ctx.workdir / 'chaperong_stage0.log'} before resuming."
        )


def entry_stage(ctx: RunContext) -> int | None:
    """Which CHAPERONg stage this replica should re-enter at, None if finished."""
    wd = ctx.workdir
    if _count_windows(wd):
        return None
    if (wd / SMD_DONE).exists():
        return 14
    return 0


def build_script(ctx: RunContext, stage: int) -> list[Step]:
    common = [
        Step(r"ENTER YOUR CHOICE HERE \(1 or 2\)", "2", label="umbrella sampling"),
        Step(r"\*Enter 1 or 2:", "1", label="protein-protein"),
        Step(r"Initiation stage:", str(stage), label=f"stage {stage}"),
    ]
    if stage != 0:
        return common

    steps = common + [
        Step(r"Do you want to proceed\? \(y(es)?/n(o)?\):", "yes",
             before=_wire_restraints, label="topology ready"),
        Step(r"ENTER A RESPONSE HERE \(1 or 2\):", "1", label="custom box"),
        Step(r"Center dimensions \(x y z\):", _center, label="box centre"),
        Step(r"Box dimensions \(x y z\):", _box, label="box vectors"),
        Step(r"ENTER A RESPONSE HERE \(1 or 2\):", "2", label="proceed to solvation"),
        Step(r"optional NVT equilibration\? \(yes/no\):", "yes", label="run NVT"),
        Step(r"custom index for pulling groups\? \(yes/no\):", "no",
             before=_make_index, label="index.ndx written by cg-us"),
    ]
    if ctx.proto.run.skip_movie:
        steps.append(Step(MOVIE_PROMPT, STOP, before=_assert_smd_finished,
                          label="stop before the SMD movie"))
    else:
        steps.append(Step(MOVIE_PROMPT, "1", label="movie, 200-300 frames"))
        steps.append(Step(r"proceed with umbrella sampling\? \(y(es)?/n(o)?\):", "yes",
                          label="start US"))
    return steps


def _session(ctx: RunContext, stage: int, timeout: int | None = None) -> dict:
    script_path, root = preflight(ctx.proto)
    steps = build_script(ctx, stage)
    log = ctx.workdir / f"chaperong_stage{stage}.log"

    env = dict(os.environ)
    env["CHAPERONg_PATH"] = str(root)
    path_parts = [str(script_path.parent)]
    shim_dir = write_pymol_shim(ctx)
    if shim_dir:
        path_parts.insert(0, str(shim_dir))
    env["PATH"] = os.pathsep.join(path_parts + [env.get("PATH", "")])

    args = ["-i", f"{ctx.prefix}.pdb", "--paraFile", "paraFile.par"]
    if ctx.proto.run.gpu:
        args.append("-g")
    if os.access(script_path, os.X_OK):
        cmd, argv = str(script_path), args
    else:
        cmd, argv = "bash", [str(script_path), *args]

    limit = timeout or ctx.proto.run.timeout_s
    transcript = open(log, "wb")
    child = pexpect.spawn(cmd, argv, cwd=str(ctx.workdir), env=env,
                          timeout=limit, encoding=None)
    child.logfile = transcript

    answered: list[str] = []
    stopped = None
    pending = list(steps)
    try:
        while pending:
            patterns = [s.pattern.encode() for s in pending] + [pexpect.EOF, pexpect.TIMEOUT]
            idx = child.expect(patterns, timeout=limit)
            if idx >= len(pending):
                reason = "timed out" if idx == len(patterns) - 1 else "exited"
                transcript.flush()
                raise RuntimeError(
                    f"CHAPERONg {reason} before prompt "
                    f"'{pending[0].label or pending[0].pattern}'\n"
                    f"full log: {log}\n{log_excerpt(log)}"
                )
            step = pending[idx]
            if step.before:
                step.before(ctx)
            if step.response is STOP:
                stopped = step.label or step.pattern
                child.terminate(force=True)
                break
            child.sendline(step.answer(ctx))
            answered.append(step.label or step.pattern)
            pending = pending[idx + 1:]
        else:
            child.expect(pexpect.EOF, timeout=limit)
    finally:
        child.close(force=True)
        transcript.close()

    return {
        "stage": stage,
        "launcher": str(script_path),
        "chaperong_path": str(root),
        "answered": answered,
        "stopped_at": stopped,
        "exit_status": child.exitstatus,
        "signal_status": child.signalstatus,
        "log": str(log),
    }


def run(ctx: RunContext, timeout: int | None = None, from_stage: int | None = None) -> dict:
    if pexpect is None:
        raise RuntimeError("pexpect is required for the CHAPERONg backend: pip install pexpect")

    stage = from_stage if from_stage is not None else entry_stage(ctx)
    sessions: list[dict] = []

    if stage is None:
        print(f"      windows already present ({_count_windows(ctx.workdir)}), nothing to run")
    else:
        if stage == 0:
            sessions.append(_session(ctx, 0, timeout))
            if sessions[-1]["stopped_at"]:
                print("      steered MD done, skipping the movie stage")
                stage = 14
            else:
                stage = None
        if stage == 14:
            sessions.append(_session(ctx, 14, timeout))

    status = {
        "sessions": sessions,
        "windows": _count_windows(ctx.workdir),
        "skip_movie": ctx.proto.run.skip_movie,
    }
    (ctx.workdir / "chaperong_status.json").write_text(json.dumps(status, indent=2))
    if not status["windows"]:
        logs = ", ".join(s["log"] for s in sessions) or "chaperong_stage*.log"
        raise RuntimeError(f"CHAPERONg produced no umbrella windows; inspect {logs}")
    return status


FATAL_RE = re.compile(r"(?i)(fatal error|error in|cannot|no such file|not found|"
                      r"segmentation fault|killed|aborted|invalid|failed)")


def log_excerpt(log: Path, tail: int = 20) -> str:
    """CHAPERONg's log with the colour codes gone and the failure surfaced."""
    if not log.exists():
        return f"(no log at {log})"
    lines = [strip_ansi(l).rstrip() for l in log.read_text(errors="ignore").splitlines()]
    lines = [l for l in lines if l.strip() and set(l.strip()) != {"#", "="}]

    fatal_at = next((i for i in range(len(lines) - 1, -1, -1) if FATAL_RE.search(lines[i])), None)
    out = []
    if fatal_at is not None:
        start = max(0, fatal_at - 4)
        out.append("  --- first sign of trouble ---")
        out += [f"  {l}" for l in lines[start:fatal_at + 8]]
    out.append("  --- last lines ---")
    out += [f"  {l}" for l in lines[-tail:]]
    return "\n".join(out)


def _count_windows(workdir: Path) -> int:
    f = workdir / "tpr_files.dat"
    if not f.exists():
        return 0
    return len([l for l in f.read_text().splitlines() if l.strip()])


def strip_ansi(text: str) -> str:
    return re.sub(r"\x1b\[[0-9;]*[A-Za-z]", "", text)
